### ISSUE TITLE
Broken animations when loading FETH G1A animation files

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#1]
Loading the FETH G1A animations worked well with [fmt_g1m](https://github.com/Joschuka/fmt_g1m) but loading the FETH G1A animation files with Project-G1M the animations appear broken.

[FETH sample files.zip](https://github.com/Joschuka/Project-G1M/files/5426309/FETH.sample.files.zip)

Can you fix it?

**Comment by Joschuka** [comment]
This works fine for me. Make sure that you don't have the additive option selected, that option is only for specific animations and will break the others.

**Comment by Andree12** [comment]
> This works fine for me. Make sure that you don't have the additive option selected, that option is only for specific animations and will break the others.

Thank you.
