### ISSUE TITLE
Touken Ranbu Warriors Demo .g1t texture files issue

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#13]
I've managed to extract the files of the game but when I load up the .g1t textures extracted from the MaterialEditor files, they don't show up properly.
[TRWarriorsDemo G1T file.zip](https://github.com/Joschuka/Project-G1M/files/7992184/TRWarriorsDemo.G1T.file.zip)
![0](https://user-images.githubusercontent.com/49048262/152290175-00b2adde-a038-488e-a2c0-657b91e53a83.png)

**Comment by Joschuka** [comment]
Looks like they finally added switch tiling after all this time.
Try this :
[projectG1M.zip](https://github.com/Joschuka/Project-G1M/files/7993334/projectG1M.zip)

**Comment by Andree12** [comment]
Well, thanks, it works

> Looks like they finally added switch tiling after all this time. Try this : [projectG1M.zip](https://github.com/Joschuka/Project-G1M/files/7993334/projectG1M.zip)

Well it works but, many other g1t textures are still having issues
[more TRWarriorsDemo G1T files.zip](https://github.com/Joschuka/Project-G1M/files/7996508/more.TRWarriorsDemo.G1T.files.zip)

**Comment by Joschuka** [comment]
I'll fix it in C++ later, in the meantime this should get most of them
[fmt_g1m.zip](https://github.com/Joschuka/Project-G1M/files/7997340/fmt_g1m.zip)

**Comment by Andree12** [comment]
> I'll fix it in C++ later, in the meantime this should get most of them [fmt_g1m.zip](https://github.com/Joschuka/Project-G1M/files/7997340/fmt_g1m.zip)

I haven't checked all of the .g1t MaterialEditor files but they do work with no flaws!

**Comment by Andree12** [comment]
You still working on it?

**Comment by Joschuka** [comment]
Yeah leave the issue open, I just need to sit down and push the fix to the dll eventually. I'll close it properly with an appropriate commit.
