### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by 805557409** [Joschuka/Project-G1M#14]
![image](https://user-images.githubusercontent.com/81523108/153704216-8832249a-ec69-4971-9ca5-3f053eb805da.png)
Excuse me, thank you very much for your plug-in. I tried to extract nioh2 character animation, but noesis can't export it. Can you tell me how to do it?

**Comment by 805557409** [comment]
Oh, I seem to have solved it, but I can't find the player animation in the nioh2 file. Do you know where it is?

**Comment by Joschuka** [comment]
Yeah I assume you had too many animations or something like that ? The next release will probably have x64 support, it should help with that.
As for the location of the files no idea sorry.
