### ISSUE TITLE
Fatal Frame 5 modded models loading crashes Noesis

### ISSUE THREAD

**Issue by Jupisoft111** [Joschuka/Project-G1M#17]
Hello again, I managed to mod several game files, but sadly whenever I try to load it with Noesis and this plugin, it crashes. But in the game they work fine without any problem, so perhaps it might need to support the format in an expanded way or something like that. Sadly even mods by other people also crash (but not all of them). The first attached file always crashes, although in game works fine. The second file never crashes somehow. Hopefully this will be useful to spot the differences. By the way I'm using Noesis version 4.464 x86. Thanks a lot and have a nice day :-)
[H_HIS_A.zip](https://github.com/Joschuka/Project-G1M/files/8566743/H_HIS_A.zip)
[H_YRI_A.zip](https://github.com/Joschuka/Project-G1M/files/8566749/H_YRI_A.zip)
[Noesis crash log.zip](https://github.com/Joschuka/Project-G1M/files/8568185/Noesis.crash.log.zip)
![2022_04_27_04_19_23_393](https://user-images.githubusercontent.com/28818179/165425975-5c143865-90d6-455f-9e40-1a28709bc8c8.png)

**Comment by Joschuka** [comment]
I'll take a look at these during the week-end. However the problem may not come from the plugin but from the modded files, some iterations of their engine may ignore fields that could be incorrect in the files and still work. 
I'll get back to you on this after a bit of investigation.

**Comment by Joschuka** [comment]
So after taking a look it seems that these model files aren't properly rebuilt, the meshes section having entries with 0 indices that I've never seen so far in proper g1m files. The game may be lenient enough to load such assets but considering how many annoying edge cases the base specs have already I prefer not supporting non compliant files for now, as I don't want to add too many workarounds.
If I ever encounter a proper g1m with the same issue I will get back to it.
