### ISSUE TITLE
Fix the model export

### ISSUE THREAD

**Issue by Mysticus92** [Joschuka/Project-G1M#19]
I extracted this model using Noesis from the game Atelier Ryza (PC), for example, with your g1m plugin and saved as dae file.
But the extracted model is so messed up, the bones aren't properly functional and the textures don't automatically load up in Blender.
![Blender 25_05_2022 10_21_23](https://user-images.githubusercontent.com/67751769/170216829-d7813760-4e60-4fca-83c9-b37b853a8237.png)

**Comment by Joschuka** [comment]
Noesis' dae exporter is quite old and Blender's dae is notoriously bad (doesn't preserve custom normals and a lot of other very weird issues).
Either way it's not a problem with the plugin, I'd recommend using fbx instead. I can't do anything about this myself.
