### ISSUE TITLE
Hyrule Warriors: Age of Calamity (DEMO) UV issues

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#2]
Several models from Hyrule Warriors: Age of Calamity (DEMO) had their UV of some meshes not loaded.
[HW Age of calamity sample files.zip](https://github.com/Joschuka/Project-G1M/files/5454486/HW.Age.of.calamity.sample.files.zip)

**Comment by Joschuka** [comment]
I noticed, I'll push a fix in the next version.

**Comment by Joschuka** [comment]
Should be fixed with bfe8d61
