### ISSUE TITLE
Fire Emblem Warriors Three Hopes Demo - g1t issues

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#20]
I got issues with the g1t files from Fire Emblem Warriors Three Hopes Demo.

Files like 74db818a0.g1t results in loading up a scrambled image.
![0](https://user-images.githubusercontent.com/49048262/173090642-7bead4ff-3b67-41ee-ad13-0e85244daa76.png)

Files like 0f8de47f.g1t immediately crashes the program due to image dimension errors.

[FEWTH g1t sample files.zip](https://github.com/Joschuka/Project-G1M/files/8879889/FEWTH.g1t.sample.files.zip)

so you gotta fix it.

**Comment by Joschuka** [comment]
Corrupted files, dump the assets using Ceth 1.2.0, not 1.2.1.
