### ISSUE TITLE
Fire Emblem Warriors Three Hopes Demo - g1m issues

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#21]
Bunch of models from this game crashes noesis:
[FEWTH g1m sample files.zip](https://github.com/Joschuka/Project-G1M/files/8880005/FEWTH.g1m.sample.files.zip)

**Comment by Joschuka** [comment]
Corrupted files, dump the assets using Ceth 1.2.0, not 1.2.1.
