### ISSUE TITLE
OPPW4- Pc,  crashes noesis when importing g1m

### ISSUE THREAD

**Issue by leostudiosTM** [Joschuka/Project-G1M#22]
it loads lightweight files that probably don't have rig, but it doesn't load anything over 1mb

[Sample.zip](https://github.com/Joschuka/Project-G1M/files/9214697/Sample.zip)

**Comment by Joschuka** [comment]
Your sample is corrupted, I assume you extracted with Cethleann 1.2.1, try with 1.2.0 instead.
When doing so I'd recommend providing the game name in the parameters, since we have a filelist for this game.
