### ISSUE TITLE
Request support for g1m ver 0x30303338 - New NUNO5 format

### ISSUE THREAD

**Issue by eArmada8** [Joschuka/Project-G1M#29]
Hi!  

Atelier Ryza 3 comes with a new version of g1m (0x30303338) and KT / Gust has changed the format of NUNO5, which now crashes your plugin.  

Here is a sample g1m set (all the g1m files can be processed normally except PC40A_default.g1m which has the new NUNO chunk)
[pc40a.zip](https://github.com/Joschuka/Project-G1M/files/11067443/pc40a.zip)

And here is the NUNO chunk isolated, in case it saves you time:
[Ryza3_NUNO_chunk.zip](https://github.com/Joschuka/Project-G1M/files/11067370/Ryza3_NUNO_chunk.zip)

I very much appreciate your plugin, I have learned quite a lot about g1m from it!

**Comment by Joschuka** [comment]
Hello,
I already added support for this new version (first used in Wild Hearts and WoLong that released recently). Your sample is working fine with the latest projectG1M release.

![image](https://user-images.githubusercontent.com/43338144/227726308-5a0db8b9-7723-4ba8-bb10-47b672d058b3.png)

**Comment by eArmada8** [comment]
I apologize, I didn't realize I was using an old version! I will take a look. I appreciate your work!
