### ISSUE TITLE
Mesh issues with Atelier Ryza 3

### ISSUE THREAD

**Issue by italonvcc** [Joschuka/Project-G1M#30]
Mesh issues when using the plugin to view/extract Atelier Ryza 3 models.

Steps to recreate:
- Extracted PAK and elixir files with Gust Tools (v1.54)
- Loaded model with Noesis v4.466 using Project-G1M v1.7.4

![image](https://user-images.githubusercontent.com/4566390/227788918-76eda9e7-74a7-4272-b701-de4f7d704a0d.png)

Sample model:
https://www.mediafire.com/file/nvy43vk8wn7idtz/pc50a.zip/file

**Comment by Joschuka** [comment]
Try the latest release.

**Comment by italonvcc** [comment]
That was crazy quick. Thank you.

**Comment by eArmada8** [comment]
Hi, the problem appears to persist.  The latest release did fix pc50a but pc48a still crashes noesis.  Thanks for looking into this!

[pc48a.zip](https://github.com/Joschuka/Project-G1M/files/11073580/pc48a.zip)

**Comment by Joschuka** [comment]
I took a closer look, the new release should work for everything now.

**Comment by eArmada8** [comment]
Thanks very much!
