### ISSUE TITLE
There's a missing seam below the chin and neck in some Fatal Frame 4 character models

### ISSUE THREAD

**Issue by Jupisoft111** [Joschuka/Project-G1M#31]
Hello, I'm not sure if this is something of the game itself (which I don't think so), something from Noesis, Gust Tools or Project G1M, but when loading a few models exported with Gust Tools into Noesis they are missing a part around their chin and neck in a way that you can even see inside the model head. Thanks a lot for all your help :-)
![2023_08_01_17_17_47_736](https://github.com/Joschuka/Project-G1M/assets/28818179/aa20bdde-bd1e-47c2-9d7a-9f866e37f908)
![2023_08_01_17_17_50_544](https://github.com/Joschuka/Project-G1M/assets/28818179/aa80b027-a225-4531-a129-627ab6a4c2b2)
![2023_08_01_17_18_01_320](https://github.com/Joschuka/Project-G1M/assets/28818179/60051eed-766a-45cb-af04-f2dd83fce966)
[H_MSK_L.zip](https://github.com/Joschuka/Project-G1M/files/12233245/H_MSK_L.zip)

**Comment by Joschuka** [comment]
Hi, the model works fine, it's just the default shader using the alpha channel in a wrong way. As I'm not processing the shader (I cannot do that in an easy way that would work for all games) and only assigning the diffuse and normal maps this sometimes happen.
Simply switch the blend mode to "None" to hide that (click a few times on the icon on the right of the skeleton icon) and it will be gone but you will also lose the hair alpha channel preview. To have some more accurate rendering, you'll have to export the model and do the shading properly in your favorite DCC Tool.
![image](https://github.com/Joschuka/Project-G1M/assets/43338144/9532b055-389d-443e-a7b4-1124149edc2e)

**Comment by Jupisoft111** [comment]
Alright then, thanks a lot for the useful info and have a nice day :-)
