### ISSUE TITLE
Problem with weights on models with more than 1000 bones.

### ISSUE THREAD

**Issue by GilAUO** [Joschuka/Project-G1M#33]
Hi, I have encountered a problem when using Project-G1M. While getting a model of Gilgamesh(0xaff23f87.g1m) in armor from the new Fate/Samurai Remnant game, I found that there are missing parts of the scales on the model especially for the tissue bones. This problem occurs mostly with models that have 1000 bones or more in them. Compared to the model of Gilgamesh in kimono (0xb256fdb9.g1m - 771 bones), there were no problems, as well as no problems with models from Fate Arcade with more than 1000 bones. I assume that the problem is in the G1M script. If possible, please check if you have the same problem.
![image](https://github.com/Joschuka/Project-G1M/assets/147229361/76eccf61-5672-4a28-984e-2e9910444f11)
![image](https://github.com/Joschuka/Project-G1M/assets/147229361/ada40d27-0e9c-42ec-8c26-ad24031ee0ff)
![image](https://github.com/Joschuka/Project-G1M/assets/147229361/f898f3c0-3622-4362-9563-d0cf2a708b68)
![image](https://github.com/Joschuka/Project-G1M/assets/147229361/200d95c2-7ae1-4fba-ad05-906e897b9afd)

**Comment by Joschuka** [comment]
The NUNO bones (that I represent in blue in Noesis) are not true bones. They are physics nodes used during cloth simulation. 
The cloth meshes aren't skinned in a standard way, they have several sets of weights to several of these nodes, used in a special vertex shader at runtime (not the usual linear skinning computation). For more details check out the source code, I emulate the vertex shader behavior to display the base pose of these meshes properly.
I only represent these nodes as bones for convenience so users can rig them in their DCC tool manually but there's no way to skin them automatically from the g1m data.
