### ISSUE TITLE
Attack on Titan 2 G1A

### ISSUE THREAD

**Issue by Cpt-Hazama** [Joschuka/Project-G1M#35]
Hello!

This plugin has worked incredibly well with the different games Ive used it on, however AOT2 G1A files cannot be opened, there's nothing put into the console window upon trying to open. It just says 'file could not be previewed.'

Any help would be appreciated!

[Examples.zip](https://github.com/Joschuka/Project-G1M/files/13472447/Examples.zip)

**Comment by Joschuka** [comment]
Hello,

Yeah you are not supposed to open them directly, you need to put your g1m file and its associated g1a animations in the same folder then open the g1m file (you need to have the "merge all" option ticked under Tools->Project G1M). The anims next to it will be loaded automatically.

**Comment by Cpt-Hazama** [comment]
Oh I see :D they work now
