### ISSUE TITLE
Certain cloth models don't rig properly

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#5]
[FETH Model Issue.zip](https://github.com/Joschuka/Project-G1M/files/6749302/FETH.Model.Issue.zip)
This includes the model that is having a issue, the animation, and the texture to it.
When the g1m file and it's animation file are loaded in FMT_G1M it rigs the cloth models properly.
But when they are loaded in the latest version of Project-G1M, it doesn't rig the cloth models properly.
Can you fix it?

**Comment by Joschuka** [comment]
Can you elaborate a bit ? 
The only difference between both is that pG1M has some very basic autorig that's just here to make physics meshes somewhat follow their driver instead of staying in place, it makes previewing animations a bit better.
You can disable this using in the options (put "enable NUN autorig" to false).

**Comment by Andree12** [comment]
> Can you elaborate a bit ?
> The only difference between both is that pG1M has some very basic autorig that's just here to make physics meshes somewhat follow their driver instead of staying in place, it makes previewing animations a bit better.
> You can disable this using in the options (put "enable NUN autorig" to false).

Here is a comparison between the three images
![1](https://user-images.githubusercontent.com/49048262/124162522-28248980-da64-11eb-975c-c42d0d7bc078.png)
![2](https://user-images.githubusercontent.com/49048262/124162537-2d81d400-da64-11eb-9450-5f6f90506739.png)
![3](https://user-images.githubusercontent.com/49048262/124162544-2fe42e00-da64-11eb-8a6d-736f0d97cd66.png)

The top image and the middle image have arms detached from the clothes, but bottom image has the arms attached with the clothes.

**Comment by Joschuka** [comment]
I can confirm the issue, I'll look into it when I have the time.

**Comment by Joschuka** [comment]
Try 9a8d144 and let me know it works. Thanks for the report, I missed that issue.

**Comment by Andree12** [comment]
> Try [9a8d144](https://github.com/Joschuka/Project-G1M/commit/9a8d144c31c1032ff315664685f93ff4b9da9deb) and let me know it works. Thanks for the report, I missed that issue.

It works, thanks!
