### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by BragonGod** [Joschuka/Project-G1M#7]
Sorry, i'm a complete idiot, i don't know how to operate this at all.

**Comment by Joschuka** [comment]
Hi,
-Download Noesis: http://richwhitehouse.com/index.php?content=inc_projects.php&showproject=91
-Put the dll that you get [here](https://github.com/Joschuka/Project-G1M/releases/latest) in the plugins directory, next to the others.
-Under Tools, click on "Display Plugin Tools" to get access to the different options.

Then you'll be able to open the files.
